export const COIN_DATA_REQUEST = "COIN_DATA_REQUEST";
export const COIN_DATA_SUCCESS = "COIN_DATA_SUCCESS";
export const COIN_DATA_FAILURE = "COIN_DATA_FAILURE";

export const FAV_COIN_DATA_REQUEST = "FAV_COIN_DATA_REQUEST";
export const FAV_COIN_DATA_SUCCESS = "FAV_COIN_DATA_SUCCESS";
export const FAV_COIN_DATA_FAILURE = "FAV_COIN_DATA_FAILURE";

export const CRYPTO_COIN_DATA_REQUEST = "CRYPTO_COIN_DATA_REQUEST";
export const CRYPTO_COIN_DATA_SUCCESS = "CRYPTO_COIN_DATA_SUCCESS";
export const CRYPTO_COIN_DATA_FAILURE = "CRYPTO_COIN_DATA_FAILURE";

export const COIN_INFO_REQUEST = "COIN_INFO_REQUEST";
export const COIN_INFO_SUCCESS = "COIN_INFO_SUCCESS";
export const COIN_INFO_FAILURE = "COIN_INFO_FAILURE";

export const GET_FAV_COINS = "GET_FAV_COINS";
export const REMOVE_FAV_COIN = "REMOVE_FAV_COIN";
export const DELETE_FAV_COINS = "DELETE_FAV_COINS";
export const FAV_COINS = "FAV_COINS";

export const GET_CRYPTO_COINS = "GET_CRYPTO_COINS";
export const GET_CRYPTO_COIN = "GET_CRYPTO_COIN";

export const GET_PREDICTION = "GET_PREDICTION";


